version: '3.7'

services:
  web2:
    build:
      context: ./
    links:
      - db:db
    command: gunicorn mon_site.wsgi:application --timeout 120 --bind 0.0.0.0:8000
    volumes:
      - static_volume_pdf:/code/blog/static
    expose:
      - 8000
    env_file: var.env
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=puydinfo.fr
      - VIRTUAL_PORT=8000
    networks:
      - site2_default

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data_pdf:/var/lib/postgresql/data/
    env_file: var.env.db
    networks:
      - site2_default

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_volume_pdf:/static
      - static_volume:/static2
    depends_on:
      - web2
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - site2_default
    links:
      - web2

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - site2_default


volumes:
  postgres_data_pdf:
  static_volume_pdf:
  static_volume:
    external: true


networks:
  site2_default:
    external: true