version: '3.7'

services:
  web2:
    build:
      context: ./
    links:
      - db:db
    command: gunicorn mon_site.wsgi:application --timeout 120 --bind 0.0.0.0:80
    volumes:
      - static_volume_pdf:/code/blog/static
    expose:
      - 80
    env_file: var.env
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=puydinfo.fr
      - VIRTUAL_PORT=8000
    networks:
      - site2_default
    deploy:
      mode: replicated
      replicas : 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    traefik.enable: 'true'
    traefik.http.routers.whoami.entrypoints: websecure
    traefik.http.routers.whoami.rule: Host(`www.puydinfo.fr`)
    traefik.http.routers.whoami.tls.certresolver: myhttpchallenge
    traefik.http.services.whoami.loadbalancer.server.port: '80'

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data_pdf:/var/lib/postgresql/data/
    env_file: var.env.db
    networks:
      - site2_default




volumes:
  postgres_data_pdf:
  static_volume_pdf:
  site2_static_volume:
    external: true
  site2_key_volume:
    external: true



networks:
  site2_default:
    external: true
