version: '3.3'

services:
  web2:
    build:
      context: ./
    links:
      - db:db
    command: gunicorn mon_site.wsgi:application --timeout 120 --bind 0.0.0.0:8000
    volumes:
      - static_volume_pdf:/code/blog/static
    expose:
      - 8000
    env_file: var.env
    depends_on:
      - db
    networks:
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web2.entrypoints=websecure"
        - "traefik.http.routers.web2.rule=Host(`www.puydinfo.fr`)"
        - "traefik.http.routers.web2.tls.certresolver=myhttpchallenge"
        - "traefik.http.services.web2.loadbalancer.server.port=8000"

  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data_pdf:/var/lib/postgresql/data/
    env_file: var.env.db
    networks:
      - default




volumes:
  postgres_data_pdf:
  static_volume_pdf:

networks:
  default:
    driver: overlay