# Generated by Django 2.1.2 on 2019-07-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price_exact',
        ),
    ]
