# Generated by Django 2.1.2 on 2019-07-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_price_exact'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
