# Generated by Django 2.1.2 on 2019-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='maj',
        ),
        migrations.AddField(
            model_name='hotel',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
