# Generated by Django 2.1.2 on 2019-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190716_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
