# Generated by Django 2.1.2 on 2019-07-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_restaurant_price_general'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price_adult',
            new_name='price_general',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='exact_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_child',
        ),
    ]
