# Generated by Django 2.1.2 on 2019-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190717_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='familly',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
