# Generated by Django 2.1.2 on 2019-07-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Group'),
        ),
    ]
