# Generated by Django 2.1.2 on 2019-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190718_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='child',
            field=models.BooleanField(default=False),
        ),
    ]
