# Generated by Django 2.1.2 on 2019-07-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_member_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('photo_home', models.ImageField(blank=True, null=True, upload_to='show_hom')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('color_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Color')),
                ('theme', models.ManyToManyField(to='blog.Theme')),
                ('type', models.ManyToManyField(to='blog.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('photo_home', models.ImageField(blank=True, null=True, upload_to='show_hom')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('color_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Color')),
                ('theme', models.ManyToManyField(to='blog.Theme')),
                ('type', models.ManyToManyField(to='blog.Type')),
            ],
        ),
    ]
