# Generated by Django 2.1.2 on 2019-07-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190725_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
