# Generated by Django 2.1.2 on 2019-07-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0016_auto_20190725_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='feed',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
