# Generated by Django 2.1.2 on 2019-07-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190725_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='object_id',
        ),
        migrations.AddField(
            model_name='feed',
            name='animation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Animation'),
        ),
        migrations.AddField(
            model_name='feed',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Hotel'),
        ),
        migrations.AddField(
            model_name='feed',
            name='resto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Restaurant'),
        ),
        migrations.AddField(
            model_name='feed',
            name='show_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Spectacle'),
        ),
        migrations.AddField(
            model_name='feed',
            name='ville_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Ville'),
        ),
    ]
