# Generated by Django 2.1.2 on 2019-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190725_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo_home',
            field=models.ImageField(blank=True, null=True, upload_to='show_hom'),
        ),
    ]
