# Generated by Django 2.1.2 on 2019-07-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190726_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sejour',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
