# Generated by Django 2.1.2 on 2019-07-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190726_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sejour',
            name='resto_midi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Restaurant'),
        ),
    ]
