# Generated by Django 2.1.2 on 2019-07-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_sejour_resto_midi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sejour',
            name='resto_soir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resto_soir', to='blog.Restaurant'),
        ),
        migrations.AlterField(
            model_name='sejour',
            name='resto_midi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resto_midi', to='blog.Restaurant'),
        ),
    ]
