# Generated by Django 2.1.2 on 2019-07-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_sejour_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sejour',
            name='resto_midi',
        ),
        migrations.RemoveField(
            model_name='sejour',
            name='resto_soir',
        ),
    ]
