# Generated by Django 2.1.2 on 2019-07-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.DeleteModel(
            name='TEST',
        ),
    ]
