# Generated by Django 2.1.2 on 2019-08-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_other'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other',
        ),
    ]
