# Generated by Django 2.1.2 on 2019-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_uploaded_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='coef_grand_show',
            field=models.TextField(blank=True),
        ),
    ]
