# Generated by Django 2.1.2 on 2019-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_programme_coef_grand_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='number',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='spectacle',
            name='number',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
