# Generated by Django 2.1.2 on 2019-08-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20190827_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='number',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='number',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
