# Generated by Django 2.1.2 on 2019-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20190827_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='name_resto_midi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programme',
            name='number_resto_midi',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
