# Generated by Django 2.1.2 on 2019-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20190827_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='i',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='programme',
            name='j',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='programme',
            name='k',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
