# Generated by Django 2.1.2 on 2019-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20190827_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='suggest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
