# Generated by Django 2.1.2 on 2019-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_programme_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='suggest',
        ),
        migrations.AlterField(
            model_name='programme',
            name='k',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
