# Generated by Django 2.1.2 on 2019-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20190828_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='suggest',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='programme',
            name='k',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
