# Generated by Django 2.1.2 on 2019-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20190828_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='name_show_midi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
