# Generated by Django 2.1.2 on 2019-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_programme_name_show_midi'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='price_show_midi',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
