# Generated by Django 2.1.2 on 2019-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_programme_price_show_midi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='i',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='j',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='k',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='number_resto_midi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='programme',
            name='price_show_midi',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
