# Generated by Django 2.1.2 on 2019-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20190828_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='name_resto_soir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programme',
            name='name_show_soir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programme',
            name='number_resto_soir',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='programme',
            name='price_show_soir',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='programme',
            name='suggest_soir',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
