# Generated by Django 2.1.2 on 2019-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20190829_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='params',
            field=models.TextField(blank=True),
        ),
    ]
