# Generated by Django 2.1.2 on 2019-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_programme_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='params',
            new_name='choix',
        ),
        migrations.AddField(
            model_name='programme',
            name='prix_max',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='prix_max_soir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='prix_min',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='prix_min_soir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='resto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='resto_soir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='resto_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='resto_type_soir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='select_resto_anime',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='select_resto_anime_soir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='temps_debut',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='temps_midi',
            field=models.TextField(blank=True),
        ),
    ]
