# Generated by Django 2.1.2 on 2019-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20190915_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='temps_form',
            field=models.TextField(blank=True),
        ),
    ]
