# Generated by Django 2.1.2 on 2019-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_programme_temps_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='choix',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prix_max',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prix_max_soir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prix_min',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prix_min_soir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='resto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='resto_soir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='resto_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='resto_type_soir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='select_resto_anime',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='select_resto_anime_soir',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='temps_debut',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='temps_form',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programme',
            name='temps_midi',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
