# Generated by Django 2.1.2 on 2019-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20190915_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='calculator',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
