# Generated by Django 2.1.2 on 2019-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_programme_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='exclus',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
