# Generated by Django 2.1.2 on 2019-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_programme_exclus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='exclus',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
